name: LinkGrabber

on:
  schedule:
    - cron: '0 */3 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write

jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test yt-dlp

        run: |
          python3 -m pip install -U "yt-dlp[default]"
          node --version
          yt-dlp --version
          yt-dlp \
            --remote-components ejs:github \
            --js-runtimes node \
            -v \
            -F \
            "https://www.youtube.com/watch?v=cb12KmMMDJA"

      - name: Grab Link

        run: |
          git config --global user.email "dp247@hll.localhost"
          git config --global user.name "dp247"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "./youtubeLink.txt is updated."
          git push